added tests for radio list
AndcultureCode/AndcultureCode.JavaScript.React.Components pull request #55
Opened 2020-10-26 14:50 UTC by SaidShah

- [x] Related GitHub issue(s) linked in PR description
- [x] Destination branch merged, built and tested with your changes
- [x] Code formatted and follows best practices and patterns
- [x] Code builds cleanly (no _additional_ warnings or errors)
- [x] Manually tested
- [x] Automated tests are passing
- [x] No _decreases_ in automated test coverage
- [x] Documentation updated (readme, docs, comments, etc.)
- [x] Localization: No hard-coded error messages in code files (_minimally_ in string constants)
- [x] New component and/ or properties? Make sure to update storybook

Closes #30

2020-10-27 14:56 UTC, jstevenson requested changes

2020-10-27 14:56 UTC, jstevenson commented on src/molecules/lists/radio-list.test.tsx
> +    COMPONENT_CLASS,
Minor: alphabetize

2020-10-27 14:56 UTC, jstevenson commented on src/molecules/lists/radio-list.test.tsx
> +    test("when items prop is empty, radio-list returns", () => {
Since `result` is null, shouldn't the name be something different than `radio-list returns`?

2020-10-27 17:17 UTC, jstevenson approved these changes

2020-10-28 01:07 UTC, brandongregoryscott requested changes
Just two pieces of feedback to consider @SaidShah. At the very least I'd like to see the component class renamed so it isn't cluttering up potential imports. 

@wintondeshong do you have any opposition for pulling in that `jest-dom`package for additional matchers?

2020-10-28 13:56 UTC, SaidShah commented
@brandongregoryscott - I made those requested changes if you would like to take a second look.

2020-10-28 14:03 UTC, wintondeshong approved these changes

2020-10-28 14:20 UTC, merged